### ISSUE TITLE
Function calling  auto-tool-choice

### ISSUE THREAD

**Issue by RRaphaell** [runpod-workers/worker-vllm#113]
when I try to deploy a llm which requires the latest update from vllm it shows:
I tried to deploy vllm localy and function calling works when I pass these arguments:   
--enable-auto-tool-choice \
 --tool-call-parser hermes \
 maybe we need the same thing here but I dont know where to add this arguments

```
2024-09-22T22:40:15.504307332Z [rank0]: Traceback (most recent call last):
2024-09-22T22:40:15.504342187Z [rank0]:   File "/src/handler.py", line 7, in <module>
2024-09-22T22:40:15.504347942Z [rank0]:     OpenAIvLLMEngine = OpenAIvLLMEngine(vllm_engine)
2024-09-22T22:40:15.504352334Z [rank0]:   File "/src/engine.py", line 122, in __init__
2024-09-22T22:40:15.504356359Z [rank0]:     asyncio.run(self._initialize_engines())
2024-09-22T22:40:15.504360651Z [rank0]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
2024-09-22T22:40:15.504364911Z [rank0]:     return loop.run_until_complete(main)
2024-09-22T22:40:15.504368929Z [rank0]:   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2024-09-22T22:40:15.504373289Z [rank0]:     return future.result()
2024-09-22T22:40:15.504377481Z [rank0]:   File "/src/engine.py", line 128, in _initialize_engines
2024-09-22T22:40:15.504381457Z [rank0]:     self.chat_engine = OpenAIServingChat(
2024-09-22T22:40:15.504385907Z [rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/serving_chat.py", line 70, in __init__
2024-09-22T22:40:15.504390268Z [rank0]:     self.chat_template = load_chat_template(chat_template)
2024-09-22T22:40:15.504394291Z [rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/chat_utils.py", line 309, in load_chat_template
2024-09-22T22:40:15.504399968Z [rank0]:     with open(chat_template, "r") as f:
2024-09-22T22:40:15.504407248Z [rank0]: TypeError: expected str, bytes or os.PathLike object, not dict
```

**Comment by RRaphaell** [comment]
@pandyamarut

**Comment by TimPietruskyRunPod** [comment]
@RRaphaell this was solved with https://github.com/runpod-workers/worker-vllm/pull/133/files#diff-a1f0665bb2f28dbb2a19a23f3e0dd505902945109f2d9326f5022abd7cb7b2b3R93-R94, so you can add this:

| env variable    | value |
| -------- | ------- |
| `ENABLE_AUTO_TOOL_CHOICE`  | `True`   |
| `TOOL_CALL_PARSER` | `hermes` or `llama3_json` or see https://docs.vllm.ai/en/latest/features/tool_calling.html  |

**Comment by nokados** [comment]
> [@RRaphaell](https://github.com/RRaphaell) this was solved with https://github.com/runpod-workers/worker-vllm/pull/133/files#diff-a1f0665bb2f28dbb2a19a23f3e0dd505902945109f2d9326f5022abd7cb7b2b3R93-R94, so you can add this:
> env variable 	value
> `ENABLE_AUTO_TOOL_CHOICE` 	`True`
> `TOOL_CALL_PARSER` 	`hermes` or `llama3_json` or see https://docs.vllm.ai/en/latest/features/tool_calling.html

this should be documented in README.md. Isn't?

**Comment by DifferentialityDevelopment** [comment]
I have ENABLE_AUTO_TOOL_CHOICE set to True, and TOOL_CALL_PARSER set to hermes, using Qwen/Qwen3-Coder-30B-A3B-Instruct-FP8
But I'm not having any luck at all getting it to work

Request:
```
{
	"input" : {
    "model": "Qwen/Qwen3-Coder-30B-A3B-Instruct-FP8",
	 	"messages" : [
			{
				"role" : "user",
				"content" : "Please try use the search_gutenberg_books tool to search for a book quick."
			}
		],
		"tool_choice": "required",
		"tools": [
			{
				"type": "function",
				"function": {
					"name": "search_gutenberg_books",
					"description": "Search for books in the Project Gutenberg library",
					"parameters": {
						"type": "object",
						"properties": {
							"search_terms": {
								"type": "array",
								"items": {"type": "string"},
								"description": "List of search terms to find books"
							}
						},
						"required": ["search_terms"]
					}
				}
			}
		]
	}
}
```

Response:
```
{
"output": [
		{
			"choices": [
				{
					"tokens": [
						"I can't actually use the search_gutenberg_books tool or any external tools to search for books in Project Gutenberg. I don't have the ability to browse the internet or access external databases.\n\nHowever, I can tell you about Project Gutenberg! It's a wonderful free library of over 70,000 free ebooks, mostly older books that are in the public domain. Some popular titles include:\n\n- \"The Adventures of Sherlock Holmes\" by Arthur Conan Doyle\n- \"Pride and Pre"
					]
				}
			],
			"usage": {
				"input": 24,
				"output": 100
			}
		}
	],
}
```
